# Generated by Django 4.2.7 on 2023-11-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
